name: get_auto_rotate_android_platform
description: Android Plugin Get Auto Rotate
repository: https://github.com/nguyenvantan25011996/get_auto_rotate_android_platform
version: 1.0.0


environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.get_auto_rotate_android_platform
        pluginClass: GetAutoRotateAndroidPlatformPlugin
